### ISSUE TITLE
I cannot add an icon.

### ISSUE THREAD

**Issue by GustyCube** [electron/fiddle#1506]
I've been trying everything to add an icon to my app, but nothing seems to be working. I have a .icns for my Mac.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
