### ISSUE TITLE
Cannot load local file.

### ISSUE THREAD

**Issue by tuansuper** [electron/fiddle#1521]
I used to add img lable to insert a picture in index.html,and I add attribute src="/asset/icon.png",But When I run it in fiddle.img label seem not to work.then I open devtools and find only a few file are loaded to /tmp directory(icon.png isn't loaded).Then I find way to solve it such as making webSecurity close,But it still don't work.Finally I run it through electron,and it works very good.So How can I let fiddle load picture

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
