### ISSUE TITLE
redo doesn't work

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#192]
OS: macOS 10.14.4

To reproduce:

1. make some changes
2. undo them with Cmd+Z
3. attempt to redo them with Cmd+Shift+Z or the 'edit -> redo' menu item

Expected behaviour:
the change is redone

Actual behaviour:
nothing happens when pressing the shortcut

**Comment by issacgerges** [comment]
I was able to trace this one back to a Monaco bug: https://github.com/microsoft/monaco-editor/issues/1782

The underlying issue is reproducible in both electron and Chrome, but curiously there are a bit inconsistent. From what I can tell, electron treats the window as unfocused when you access the menus, while in Chrome I actually need to switch away from the app and then switch back to reproduce.

**Comment by dsanders11** [comment]
This doesn't repro for me on the latest, so I'm going to close it as having been fixed at some point.
