### ISSUE TITLE
Fiddle v0.7.0 broken?

### ISSUE THREAD

**Issue by miniak** [electron/fiddle#199]
After upgrading to v0.7.0, Fiddle is not usable (the editors don't show up).
I've also tried downloading and reinstalling manually, still the same problem.

The developer console shows these errors:
<img width="1508" alt="Screen Shot 2019-05-17 at 9 47 41 AM" src="https://user-images.githubusercontent.com/1281234/57911760-ebe43e00-7888-11e9-83d7-c948d33d819e.png">
Going back to v0.6.0 fixes the issue for me.

**Comment by felixrieseberg** [comment]
We had a pretty nasty error because `monaco-editor` is both a devDependency (for TypeScript) and a normal dependency (as a sub-dependency of `monaco-loader`). The latest `electron-forge` decided to purge it in the build.

The issue should now be fixed - are you still having trouble with the re-tagged https://github.com/electron/fiddle/releases/tag/v0.7.0?

**Comment by miniak** [comment]
Works now!
