### ISSUE TITLE
Feature Request: console resizing

### ISSUE THREAD

**Issue by codebytere** [electron/fiddle#215]
Sometimes it's desirable to be able to see more or less of the console output at any given time, like when there's a long error message or stacktrace.

It'd be awesome if the console window was horizontally resizable using the same type of drag controls that the editors have!

**Comment by DeerMichel** [comment]
A quick workaround would be to add following css to the output div `resize: vertical;`. (I assume you meant vertical resizing.)

However, there are two problems with that:
- resizing the console is very laggy (for whatever reason)
- style doesnt match the drag controls of the editor - i think that needs much effort since the drag controls are Monaco-specific
