### ISSUE TITLE
Unable to select folder in local Electron build dialog

### ISSUE THREAD

**Issue by LOVELIBERTY1314** [electron/fiddle#269]
picture1:
![image](https://user-images.githubusercontent.com/35516695/68037047-e1681480-fd01-11e9-89bf-5808e29b6ec9.png)
picture2:
![image](https://user-images.githubusercontent.com/35516695/68037136-08264b00-fd02-11e9-9e9f-242a187db551.png)
I can't add local Electron bulid in Electron setting. As you see in picture1 and picture 2 .The `F:\Program-Files\Electron` have included `electron.exe`, but The picture 1 show that `We did not find a electron.exe  in this folder...`. How can I solve this Problem?

**Comment by erickzhao** [comment]
I get the same error when trying to import a folder. It seems like selecting a folder with the File Input selects some arbitrary file in the folder (in your case `chrome_100_percent.pak`) rather than the folder itself.

I just tested, and this feature works in Fiddle `0.10.0`, but seems like it broke on the latest release.

Thanks for the report, I'll investigate today!

**Comment by erickzhao** [comment]
This PR in particular seems to be the culprit:
https://github.com/electron/electron/pull/18343

I'll try to add a PR in today! For now, sticking to Electron Fiddle v0.10.0 should be a safe bet to adding local versions. Thanks again for the report, @LOVELIBERTY1314.

**Comment by LOVELIBERTY1314** [comment]
> This PR in particular seems to be the culprit:
> [electron/electron#18343](https://github.com/electron/electron/pull/18343)
> 
> I'll try to add a PR in today! For now, sticking to Electron Fiddle v0.10.0 should be a safe bet to adding local versions. Thanks again for the report, @LOVELIBERTY1314.

Thank you for your help.
