### ISSUE TITLE
Menu version picker broken

### ISSUE THREAD

**Issue by codebytere** [electron/fiddle#632]
On the latest release, if you start with a local version (e.g.`999.0`) then try to select a release, you see:

<img width="572" alt="Screen Shot 2021-03-30 at 2 32 47 PM" src="https://user-images.githubusercontent.com/2036040/112989063-5f0f9a00-9119-11eb-9b3b-d173c2ba06be.png">

However, when you click `Yes` the version says the same and the Fiddle does not change. It _does_ change, however, when you click `Cancel`. Looks like these got swapped somehow.

**Comment by codebytere** [comment]
Looks like this only happens sometimes, too 🤔

**Comment by ckerr** [comment]
This is probably due to the changes in renderer/content.ts in the last release, but I'm not seeing it yet.

@codebytere to make sure I'm understanding the steps right, what I think you're saying is you:

1. Start Electron Fiddle, current Electron version is 999.0.0, current fiddle is the default startup fiddle
2. Without editing anything (i.e. the editors are still showing the default startup fiddle) you select another Electron release via the version dropdown on the upper right in the main window, e.g. 12.0.2 (and if this is correct, it _may_ matter if it's a branch with a stable release or not; do you remember the version?)
3. You get this prompt in the screenshot, "Openig this Fiddle will replace..." and you click "Yes" to replace
4. The dialog disappears but the editors & electron version are unchanged.

Do each of those lines sound correct?

Also, if when you see this happen, if you open up the devtools via Help > Toggle Devtools, do you see any error messages there?

**Comment by ckerr** [comment]
Followup: My guess is that the logic didn't get switched, since the dialog code didn't change any. However the code right after it _did_ change some. So maybe what's happening is the dialog is fine but we're hitting an exception after the dialog closes but before the version changes. @codebytere could you trigger this bug again and check devtools for errors?

**Comment by codebytere** [comment]
Closing as i've not been able to repro this again but if it recurs i'll re-open!
