### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by duckida** [electron/fiddle#716]
I have this app on my raspberry pi but i need to delete it. How do I uninstall?

**Comment by malept** [comment]
Depends on how you installed Electron Fiddle.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
